# Site settings
title: Musings
header-img: img/home-bg.png
email: mark.aubuchon@gmail.com
copyright_name: aubuchon44
description: > # this means to ignore newlines until "baseurl:"
  of a coding and programming
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  aubuchon44
learn_profile: aubuchon44
email_username: mark.aubuchon@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
